### ISSUE TITLE
add new user

### ISSUE THREAD

**Issue by elhb** [jsbroks/coco-annotator#188]
Hi,
I think the line:
https://github.com/jsbroks/coco-annotator/blob/391171614e90d73d50516d4e2e5bb6fe8d9d5c60/backend/webserver/api/admin.py#L70

should be changed to:
`if UserModel.objects(username__iexact=username).first():`

Otherwise you get the following error when you try to create a new user:
Traceback (most recent call last):
  File ".../site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".../site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File ".../site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File ".../site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File ".../site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File ".../coco-annotator/workspace/webserver/api/admin.py", line 70, in post
    if User.objects(username__iexact=username).first():
AttributeError: type object 'User' has no attribute 'objects'

**Comment by jsbroks** [comment]
Yup, guess I missed it in the refactoring

**Comment by jsbroks** [comment]
Fixed. Thanks!
