### ISSUE TITLE
v0.10.2 - symbolic link folders not supported?

### ISSUE THREAD

**Issue by EMCP** [jsbroks/coco-annotator#193]
attempting now to place a symbolic link inside the `dataset/` area, but nothing seems to get picked up.. furthermore trying the trick of creating a dataset with the same name as the folder is blocked due to the folder already existing.. leaving me stuck with nothing loaded.

Question is, are symbolic link folders supported for storing datasets?  

I am running on a mac, with `v 0.10.2` and `docker-compose up` to get started

```
annotator_webclient | [2019-04-17 22:07:32 +0000] [11] [DEBUG] POST /api/dataset/
annotator_webclient | [2019-04-17 22:07:32 +0000] [11] [ERROR] Exception on /api/dataset/ [POST]
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
annotator_webclient |     rv = self.dispatch_request()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
annotator_webclient |     resp = resource(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
annotator_webclient |     return self.dispatch_request(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
annotator_webclient |     resp = meth(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
annotator_webclient |     return func(*args, **kwargs)
annotator_webclient |   File "/workspace/webserver/api/datasets.py", line 77, in post
annotator_webclient |     dataset.save()
annotator_webclient |   File "/workspace/database/datasets.py", line 34, in save
annotator_webclient |     os.makedirs(directory)
annotator_webclient |   File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
annotator_webclient |     mkdir(name, mode)
annotator_webclient | FileExistsError: [Errno 17] File exists: '/datasets/output_images/'
annotator_webclient | [2019-04-17 22:07:36 +0000] [11] [DEBUG] GET /api/dataset/data

```

**Comment by jsbroks** [comment]
Wired.. I changed the code a bit to see if that fixes the issue.

You'll have to wait for the docker image to build (about an hour) and then in the docker-compose file change from `web-server:stable` to `web-server:latest`

**Comment by EMCP** [comment]
I think I will go ahead and close, haven't tried to directly use symbolic links and do not know when I can get to testing it again
