### ISSUE TITLE
v0.10.2 - crash when attempting to get annotations from previous image

### ISSUE THREAD

**Issue by EMCP** [jsbroks/coco-annotator#195]
I have a dataset, with an image.  I have previously annotated the prior image... and want to copy those over to the one I am looking at.. I click copy annotation.. clicked "previous image" and get a client side error...

looked at the console to find this

```
annotator_webclient | [2019-04-22 16:54:22 +0000] [184] [DEBUG] POST /api/image/copy/333/135/annotations
annotator_webclient | [2019-04-22 16:54:22 +0000] [184] [ERROR] Exception on /api/image/copy/333/135/annotations [POST]
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
annotator_webclient |     rv = self.dispatch_request()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
annotator_webclient |     resp = resource(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
annotator_webclient |     return self.dispatch_request(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
annotator_webclient |     resp = meth(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
annotator_webclient |     return func(*args, **kwargs)
annotator_webclient |   File "/workspace/webserver/api/images.py", line 190, in post
annotator_webclient |     return {'annotations_created': image_to.copy_annotations(query)}
annotator_webclient |   File "/workspace/database/images.py", line 148, in copy_annotations
annotator_webclient |     clone = annotation.clone()
annotator_webclient |   File "/workspace/database/annotations.py", line 93, in clone
annotator_webclient |     create = json.loads(self.to_json())
annotator_webclient | NameError: name 'json' is not defined

```

**Comment by jsbroks** [comment]
Forgot to import `json` module

**Comment by EMCP** [comment]
if and when I upgrade to a latest release of this, is the database and my work preserved.. I think I will do 1 export soon of 600 images.. using `v0.10.2` .. but wondering if it's safe to just continue working.. I guess technically since it's able to import/export.. I can export all my current work, then try importing into latest release

**Comment by jsbroks** [comment]
Always when upgrading create an export of your annotations! At the very worse you can import the annotations.

If a version release will cause incompatibility issues a note will be made in the release information (rarely will maybe).
