### ISSUE TITLE
Import COCO Format Annotations into dataset and other tasks won't start

### ISSUE THREAD

**Issue by schwabse** [jsbroks/coco-annotator#216]
I managed to create and run the current docker-container. I created a dataset with some images, now I try to "Import COCO" from another dataset. Nothing happens after selecting the corresponding JSON. I note, that under the Task section, some tasks are queued already. However, they have never been started (although tasks are marked "running").

Is there a way to trigger the execution of those tasks? 
 
![image](https://user-images.githubusercontent.com/22539619/59848206-dcaf4f00-9364-11e9-9476-e7f145a805a9.png)

Clicking on the task shows no log info.

**Comment by schwabse** [comment]
Mhmh, after restarting the server everything seems to work, now and the import works well. 

It looks like a worker has not been found in the previous iteration. Would be good feedback to user if this is the case. 

Now import works: 

```
annotator_message_q | 2019-06-20 12:51:57.581 [info] <0.649.0> accepting AMQP connection <0.649.0> (172.19.0.5:37874 -> 172.19.0.3:5672)               │                                                                                │nect
annotator_message_q | 2019-06-20 12:51:57.586 [info] <0.649.0> connection <0.649.0> (172.19.0.5:37874 -> 172.19.0.3:5672): user 'user' authenticated an│Setup            Left column          Right column         Available meters     │    return self.connection
d granted access to vhost '/'                                                                                                                          │Meters          0;10m CPUs (1/2) [Bar]     CPUs (2/2) [Bar]     Clock              File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 823, in conannotator_workers | [2019-06-20 12:51:57,599: INFO/MainProcess] Received task: workers.tasks.data.import_annotations[e4b4ded6-e34b-4cb1-a70c-a77281acd1│Display options  Memory [Bar]         Task counter [Text]  Load averages: 1 minu│nection
55]                                                                                                                                                    │Colors           Swap [Bar]           Load average [Text]  Load: average of read│    self._connection = self._establish_connection()
annotator_workers | /usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges│Columns                               Uptime [Text]        Memory               │  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 778, in _es: this is                                                                                                                                              │                                                           Swap                 │tablish_connection
annotator_workers | absolutely not recommended!                                                                                                        │                                                           Task counter         │    conn = self.transport.establish_connection()
annotator_workers |                                                                                                                                    │                                                           Uptime               │  File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, annotator_workers | Please specify a different user using the --uid option.                                                                            │                                                           Battery              │in establish_connection
annotator_workers |                                                                                                                                    │                                                           Hostname             │    conn.connect()
annotator_workers | User information: uid=0 euid=0 gid=0 egid=0                                                                                        │                                                           CPUs (1/1): all CPUs │  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 307, in connannotator_workers |                                                                                                                                    │                                                           CPUs (1&2/2): all CPU│ect
annotator_workers |   uid=uid, euid=euid, gid=gid, egid=egid,                                                                                          │                                                           CPUs (1/2): first hal│    self.transport.connect()
annotator_workers | [2019-06-20 12:51:57,616: WARNING/ForkPoolWorker-8] /usr/local/lib/python3.6/site-packages/pymongo/topology.py:149: UserWarning: Mo│                                                           CPUs (2/2): second ha│  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 81, in connecngoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq│                                                           CPUs (1&2/4): first h│t
.html#is-pymongo-fork-safe                                                                                                                             │                                                           CPUs (3&4/4): second │    self._connect(self.host, self.port, self.connect_timeout)
annotator_workers |   "MongoClient opened before fork. Create MongoClient only "                                                                       │                                                           Blank                │  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 152, in _connannotator_workers | [2019-06-20 12:51:57,657: INFO/ForkPoolWorker-8] Server initialized for eventlet.                                                  │                                                           CPU average          │ect
annotator_workers | [2019-06-20 12:51:57,674: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                           CPU 1                │    "failed to resolve broker hostname"))
annotator_message_q | 2019-06-20 12:51:57.687 [info] <0.661.0> accepting AMQP connection <0.661.0> (172.19.0.4:38986 -> 172.19.0.3:5672)               │                                                           CPU 2                │OSError: failed to resolve broker hostname
annotator_message_q | 2019-06-20 12:51:57.691 [info] <0.661.0> connection <0.661.0> (172.19.0.4:38986 -> 172.19.0.3:5672): user 'user' authenticated an│                                                           CPU 3                │Sleeping 32.0s
d granted access to vhost '/'                                                                                                                          │                                                           CPU 4                │Traceback (most recent call last):
annotator_workers | [2019-06-20 12:51:57,699: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                           CPU 5                │  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 141, in _connannotator_workers | [2019-06-20 12:51:57,705: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                           CPU 6                │ect
annotator_workers | [2019-06-20 12:51:57,714: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                           CPU 7                │    host, port, family, socket.SOCK_STREAM, SOL_TCP)
annotator_workers | [2019-06-20 12:51:57,739: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                                                                                      CPU 8                │  File "/usr/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 53annotator_workers | [2019-06-20 12:51:57,753: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                                                │7, in getaddrinfo
annotator_workers | [2019-06-20 12:51:57,766: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                                                │    raise socket.gaierror(socket.EAI_NONAME, 'No address found')
annotator_workers | [2019-06-20 12:51:57,779: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                                                │socket.gaierror: [Errno -2] No address found
annotator_workers | [2019-06-20 12:51:57,791: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                                                │[K
annotator_workers | [2019-06-20 12:51:57,804: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]                                          │                                                                                │DuDuring handling of the above exception, another exception occurred:
annotator_workers | [2019-06-20 12:51:57,820: INFO/ForkPoolWorker-8] Task workers.tasks.data.import_annotations[e4b4ded6-e34b-4cb1-a70c-a77281acd155] s│                                                                                │
ucceeded in 0.21577743200032273s: None
```

**Comment by jsbroks** [comment]
Clicking on the task shows some logs
