### ISSUE TITLE
Cannot execute "download COCO" when annotating key points

### ISSUE THREAD

**Issue by YuSakaii** [jsbroks/coco-annotator#236]
Dataset with keypoints and segmentation annotations could not be downloaded.
Dataset annotated with segmentation only could be downloaded.

````
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
annotator_webclient |     rv = self.dispatch_request()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
annotator_webclient |     resp = resource(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
annotator_webclient |     return self.dispatch_request(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
annotator_webclient |     resp = meth(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
annotator_webclient |     return func(*args, **kwargs)
annotator_webclient |   File "/workspace/webserver/api/datasets.py", line 477, in get
annotator_webclient |     return coco_util.get_dataset_coco(dataset)
annotator_webclient |   File "/workspace/webserver/util/coco_util.py", line 222, in get_dataset_coco
annotator_webclient |     arr = np.array(annotation.get('keypoints', []))
annotator_webclient | NameError: name 'np' is not defined
````

OS: MacOS 10.14.3

**Comment by jsbroks** [comment]
How are you downloading the annotation data? Are you using the dropdown download button?

**Comment by mgarbade** [comment]
I followed your advice and used the `Export COCO` button, however I still cannot find any annotation file in my workspace or dataset folder 

Here the messages from coco-annotator after pressing `export`

```
annotator_workers | [2019-09-13 18:00:56,532: INFO/MainProcess] Received task: workers.tasks.data.export_annotations[35b15421-fe79-4e84-ab6f-90e911d803f5]  
annotator_workers | /usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
annotator_workers | absolutely not recommended!
annotator_workers | 
annotator_workers | Please specify a different user using the --uid option.
annotator_workers | 
annotator_workers | User information: uid=0 euid=0 gid=0 egid=0
annotator_workers | 
annotator_workers |   uid=uid, euid=euid, gid=gid, egid=egid,
annotator_workers | [2019-09-13 18:00:56,541: WARNING/ForkPoolWorker-2] /usr/local/lib/python3.6/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
annotator_workers |   "MongoClient opened before fork. Create MongoClient only "
annotator_workers | [2019-09-13 18:00:56,583: INFO/ForkPoolWorker-2] Server initialized for eventlet.
annotator_workers | [2019-09-13 18:00:56,598: INFO/ForkPoolWorker-2] emitting event "taskProgress" to all [/]
annotator_message_q | 2019-09-13 18:00:56.604 [info] <0.511.0> accepting AMQP connection <0.511.0> (172.18.0.4:38086 -> 172.18.0.2:5672)
annotator_message_q | 2019-09-13 18:00:56.609 [info] <0.511.0> connection <0.511.0> (172.18.0.4:38086 -> 172.18.0.2:5672): user 'user' authenticated and granted access to vhost '/'
annotator_workers | [2019-09-13 18:00:56,612: INFO/ForkPoolWorker-2] emitting event "taskProgress" to all [/]
annotator_workers | [2019-09-13 18:00:56,621: INFO/ForkPoolWorker-2] emitting event "taskProgress" to all [/]
annotator_workers | [2019-09-13 18:00:56,631: INFO/ForkPoolWorker-2] Task workers.tasks.data.export_annotations[35b15421-fe79-4e84-ab6f-90e911d803f5] succeeded in 0.0978977179620415s: None
annotator_webserver | [2019-09-13 18:00:57 +0000] [10] [DEBUG] GET /api/dataset/1/exports
annotator_webserver | [2019-09-13 18:00:57 +0000] [10] [DEBUG] Closing connection. 

```

**Comment by mgarbade** [comment]
The downloading of keypoint annotations works. 
- first annotate an arbitrary region (brush, polygon, etc) as 'person'
- then annotate all 17 keypoints using the keypoint tool
- select the "Datasets" tab 
- open your dataset
- click "Export COCO"
- then click on the "Exports" tab in the bar containing "Images" "Exports" "Members" ... "Settings"
- there click the "Download" button

**Comment by kevdagoat** [comment]
This is very annoying as I would like to use this route in a Python script for grabbing annotations.

I have tried adding:
```
import numpy as np
```

But sadly it still says it is not defined, this could be my container though.

**Comment by jsbroks** [comment]
That endpoint is deprecated. Use the `/exports` end points.

**Comment by kevdagoat** [comment]
Ok Sent from Mail for Windows 10 From: Justin BrooksSent: Tuesday, October 8, 2019 12:04 PMTo: jsbroks/coco-annotatorCc: Kevdagoat; CommentSubject: Re: [jsbroks/coco-annotator] Cannot execute "download COCO" when annotating key points (#236) That endpoint is deprecated. Use the /exports end points.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
