### ISSUE TITLE
Thumbnails are missing annotations immediately following COCO import

### ISSUE THREAD

**Issue by desireB** [jsbroks/coco-annotator#242]
Similar to the issue : https://github.com/jsbroks/coco-annotator/issues/130 

Hi. It looks like the issue is still there.
Under categories http://localhost:5000/#/categories , I can see that they have all been imported.

The logs from the console:
```
annotator_webclient | ValueError: cannot reshape array of size 1 into shape (2)
annotator_webclient | [2019-08-26 20:06:25 +0000] [10] [ERROR] Exception on /api/image/23 [GET]
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
annotator_webclient |     rv = self.dispatch_request()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
annotator_webclient |     resp = resource(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
annotator_webclient |     return self.dispatch_request(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
annotator_webclient |     resp = meth(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
annotator_webclient |     return func(*args, **kwargs)
annotator_webclient |   File "/workspace/webserver/api/images.py", line 135, in get
annotator_webclient |     pil_image = image.thumbnail() if thumbnail else Image.open(image.path)
annotator_webclient |   File "/workspace/database/images.py", line 103, in thumbnail
annotator_webclient |     pil_image = self.generate_thumbnail()
annotator_webclient |   File "/workspace/database/images.py", line 130, in generate_thumbnail
annotator_webclient |     image = self().draw(color_by_category=True, bbox=False)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/imantics/image.py", line 183, in draw
annotator_webclient |     annotation.mask.draw(temp_image, alpha=alpha, color=color)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/imantics/annotation.py", line 132, in mask
annotator_webclient |     self._c_mask = self.polygons.mask(width=self.width, height=self.height)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/imantics/annotation.py", line 624, in mask
annotator_webclient |     mask = cv2.fillPoly(mask, self.points, 1)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/imantics/annotation.py", line 676, in points
annotator_webclient |     for point in self.polygons
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/imantics/annotation.py", line 676, in <listcomp>
annotator_webclient |     for point in self.polygons
annotator_webclient | ValueError: cannot reshape array of size 1 into shape (2)
```

**Comment by matt-deboer** [comment]
@desireB This appears to be a different problem; in this case, the code is actually attempting to generate a thumbnail (which was not happening at all in the old issue)--but the thumbnail generation is failing.

This _may_ be due to an unexpected/invalid annotation, but I can't tell without a sample of the data. Could you provide a minimal sample coco.json which triggers this error?
