### ISSUE TITLE
Only lists and tuples may be used in a list field: ['segmentation']

### ISSUE THREAD

**Issue by mgarbade** [jsbroks/coco-annotator#249]
I tried to import the COCO `person_keypoints_val2017.json` file and images to the coco-annotator. 
- I first created a dataset  `coco`, placed all images of val2017 inside the /datasets/coco folder
- Then I imported  `person_keypoints_val2017.json`
- Towards the very end of the importing process, I get the following error message:

```
annotator_webserver | [2019-09-16 10:43:32 +0000] [10] [DEBUG] GET /api/image/2733
annotator_webserver | [2019-09-16 10:43:32 +0000] [10] [DEBUG] Closing connection. 
annotator_webserver | [2019-09-16 10:43:32 +0000] [10] [DEBUG] GET /api/image/4626
annotator_webserver | [2019-09-16 10:43:32 +0000] [10] [DEBUG] Closing connection. 
annotator_workers | [2019-09-16 10:43:40,574: INFO/ForkPoolWorker-8] emitting event "taskProgress" to all [/]
annotator_message_q | 2019-09-16 10:43:42.831 [error] <0.501.0> closing AMQP connection <0.501.0> (172.18.0.5:39308 -> 172.18.0.3:5672):
annotator_message_q | missed heartbeats from client, timeout: 60s
annotator_workers | [2019-09-16 10:44:01,011: ERROR/ForkPoolWorker-8] Task workers.tasks.data.import_annotations[aea8157b-3f48-4ca7-9b1f-13ac4afb927e] raised unexpected: ValidationError(ValidationError (AnnotationModel:10807) (Only lists and tuples may be used in a list field: ['segmentation']),)
annotator_workers | Traceback (most recent call last):
annotator_workers |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
annotator_workers |     R = retval = fun(*args, **kwargs)
annotator_workers |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
annotator_workers |     return self.run(*args, **kwargs)
annotator_workers |   File "/workspace/workers/tasks/data.py", line 266, in import_annotations
annotator_workers |     annotation_model.save()
annotator_workers |   File "/workspace/database/annotations.py", line 77, in save
annotator_workers |     return super(AnnotationModel, self).save(*args, **kwargs)
annotator_workers |   File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 369, in save
annotator_workers |     self.validate(clean=clean)
annotator_workers |   File "/usr/local/lib/python3.6/site-packages/mongoengine/base/document.py", line 392, in validate
annotator_workers |     raise ValidationError(message, errors=errors)
annotator_workers | mongoengine.errors.ValidationError: ValidationError (AnnotationModel:10807) (Only lists and tuples may be used in a list field: ['segmentation'])
```

My idea was to import some COCO data and the corresponding annotation file to make sure that my own annotations are 100% compatible with the existing COCO format.

**Comment by mgarbade** [comment]
Despite the above mentioned error. The importing is working, after I 
- click on Datasets -> Select Daset -> 3 Dots -> Edit 
- add the `Person`  and it's respective 17  keypoints (nose, eyes, etc) to the dataset. 
In the beginning images are still marked as 'not annotated' but upon opening the images individually the coco-annotations finally get loaded correctly
