### ISSUE TITLE
v0.10.6 - Using Eraser or Brush Tool leads to fatal crash of annotator_webclient

### ISSUE THREAD

**Issue by schwabse** [jsbroks/coco-annotator#268]
When manipulating/correcting already created annotations using the Eraser Tool may lead to a fatal crash of _annotator_webclient,_ which can be recovered by restarting the server. 

The issue seems to occur only after a certain time, let's say after about an hour of working on images or about 120 annotations made. 

This problem leads ultimately to status 500.

**EDIT:** 
The issue seems to be related to a large number (several dozen?) of vertices of the polygons created while brushing or erasing an area. 

I obtained some logs from  _annotator_webclient,_  that could be of some use for debugging. However, I was not able to determine the root cause. Hope this helps: 

```annotator_webclient | [2019-10-14 08:28:48 +0000] [10] [DEBUG] POST /api/annotator/data                                                 
annotator_webclient | [2019-10-14 08:28:48 +0000] [10] [ERROR] Exception on /api/annotator/data [POST]                                  
annotator_webclient | Traceback (most recent call last):                                                                                
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request                 
annotator_webclient |     rv = self.dispatch_request()                                                                                  
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request                      
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)                                                    
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper                       
annotator_webclient |     resp = resource(*args, **kwargs)                                                                              
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view                                  
annotator_webclient |     return self.dispatch_request(*args, **kwargs)                                                                 
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request          
annotator_webclient |     resp = meth(*args, **kwargs)                                                                                  
annotator_webclient |   File "/workspace/webserver/util/__init__.py", line 10, in wrap                                                  
annotator_webclient |     result = func(*args, **kwargs)                                                                                
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view                 
annotator_webclient |     return func(*args, **kwargs)                                                                                  
annotator_webclient |   File "/workspace/webserver/api/annotator.py", line 44, in post                                                  
annotator_webclient |     db_dataset.update(annotate_url=dataset.get('annotate_url', ''))                                               
annotator_webclient | AttributeError: 'NoneType' object has no attribute 'update'                                                       
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /                                                                    
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [INFO] Socket connection has been disconnected with jemonds                      
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] Closing connection.                                                      
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /socket.io/                                                          
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [INFO] Socket connection created with jemonds                                    
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /api/user/                                                           
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /api/info/                                                           
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /api/dataset/4/data                                                  
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /socket.io/                                                          
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /socket.io/                                                          
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [ERROR] Exception on /api/dataset/4/data [GET]                                   
annotator_webclient | Traceback (most recent call last):                                                                                
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request                 
annotator_webclient |     rv = self.dispatch_request()                                                                                  
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request                      
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)                                                    
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 329, in wrapper                       
annotator_webclient |     return self.make_response(data, code, headers=headers)                                                        
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 350, in make_response                 
annotator_webclient |     resp = self.representations[mediatype](data, *args, **kwargs)                                                 
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/representations.py", line 25, in output_json        
annotator_webclient |     dumped = dumps(data, **settings) + "\n"                                                                       
annotator_webclient |   File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps                                            
annotator_webclient |     return _default_encoder.encode(obj)                                                                           
annotator_webclient |   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode                                            
annotator_webclient |     chunks = self.iterencode(o, _one_shot=True)                                                                   
annotator_webclient |   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode                                        
annotator_webclient |     return _iterencode(o, 0)                                                                                      
annotator_webclient |   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default                                           
annotator_webclient |     o.__class__.__name__)                                                                                         
annotator_webclient | TypeError: Object of type 'set' is not JSON serializable                                                          
annotator_webclient | [2019-10-14 08:28:52 +0000] [10] [DEBUG] GET /favicon.ico```

**Comment by mubashirhanif** [comment]
The logs seems to come from the `annotator_webserver` rather then `annotator_webclient`. There are 2 errors in general, the first is when it tries to create/save data from the annotator client. here the error comes from what seems to be a typo in `api/annotator.py` at [line 41](https://github.com/jsbroks/coco-annotator/blob/a4db2b2f958721764c1ae5ca7d8fa8536f608247/backend/webserver/api/annotator.py#L41) , that is checking `dataset` instead of `db_dataset`, this needs to be fixed, @jsbroks your thoughts?

while the second part I am a bit clueless since the traceback doesn't point to an exact failure point in our code, so my guess based on the fact that its trying to make a response and is stuck at the encoding part, means that somewhere in the response object there is a `set` type object, I tried to execute the script on my own and couldn't find this potential set object.

**Comment by jsbroks** [comment]
You are probabaly correct, the check should be for `db_dataset`.

The second problem is for some reason, one of the variables being return in [`/dataset/<id>/data`](https://github.com/jsbroks/coco-annotator/blob/a4db2b2f958721764c1ae5ca7d8fa8536f608247/backend/webserver/api/datasets.py#L319) is a [set](https://docs.python.org/3.8/library/stdtypes.html#set-types-set-frozenset), not a list, so flask rest cannot convert it correctly into JSON.

**Comment by jsbroks** [comment]
Not sure how to reproduce this issue, so it's hard to debug

**Comment by schwabse** [comment]
I put two hours into recreation efforts for this bug, and I was not able to recreate that particular error message on the server. 

The server docker image is called `jsbroks/coco-annotator:webserver-stable` the running container is named `annotator_webclient`, this is maybe a bit confusing. 

It is however pretty easy to bring the client to a crash by brushing like a hundred circles with radius set to 300 by swooshing over the screen (Lots of vertices created, but not too many. Works like a charm, btw...) And then deleting only some vertices by using the "erase tool" by applying multiple clicks. A good dozen or so. On machines with 8GB RAM this brings the page to a fatal crash. On machines with 32GB the site freezes, basically fatal too. However, I suppose a client issue here. Not a server issue. Different bug? Same result for the user. 

We have relative big image matrices, like 2000x3000 and some bigger Polygons to correct for. Being not able to use the "erase tool" to correct, but rather deleting previous work is a big one for us. 

Any recommendations what to do to solve the issue? 

(I tend to close this issue and open a new one?!)

**Comment by jsbroks** [comment]
Sounds like the same issue as #210

**Comment by schwabse** [comment]
I'd recommend closing this one, and I report if I observe the original server crash again.

**Comment by jsbroks** [comment]
We can always reopen
