### ISSUE TITLE
v0.10.6 - Error on labels with non-english labels

### ISSUE THREAD

**Issue by EMCP** [jsbroks/coco-annotator#272]
I have a label set which utilize character sets from Sweden.. it, I think, is causing errors when I attempt to download the COCO annotations

```
annotator_webclient | UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 180: ordinal not in range(128)
annotator_webclient | [2019-10-15 21:07:05 +0000] [36] [DEBUG] GET /api/export/10/download
annotator_webclient | [2019-10-15 21:07:05 +0000] [36] [ERROR] Error handling request /api/export/10/download
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
annotator_webclient |     self.handle_request(listener_name, req, client, addr)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 112, in handle_request
annotator_webclient |     resp.write_file(respiter)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 405, in write_file
annotator_webclient |     self.write(item)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 333, in write
annotator_webclient |     self.send_headers()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
annotator_webclient |     util.write(self.sock, util.to_bytestring(header_str, "ascii"))
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 507, in to_bytestring
annotator_webclient |     return value.encode(encoding)
annotator_webclient | UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 184: ordinal not in range(128)
annotator_message_q | 2019-10-15 21:07:47.465 [error] <0.22431.0> closing AMQP connection <0.22431.0> (172.18.0.5:45870 -> 172.18.0.3:5672):
```

**Comment by EMCP** [comment]
example labels are

```
äpple
ingefära

```
