### ISSUE TITLE
pymongo.errors.InvalidName: database names cannot contain the character ' '

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#285]
It seems that the database name of 'Celery Worker' is invalid in the recent version of pymongo.
This is easily resolved by removing the space.

```
annotator_webclient | [2019-11-11 21:49:15 +0000] [10] [ERROR] Exception in worker process
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
annotator_webclient |     worker.init_process()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
annotator_webclient |     super(EventletWorker, self).init_process()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
annotator_webclient |     self.load_wsgi()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
annotator_webclient |     self.wsgi = self.app.wsgi()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
annotator_webclient |     self.callable = self.load()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
annotator_webclient |     return self.load_wsgiapp()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
annotator_webclient |     return util.import_app(self.app_uri)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
annotator_webclient |     __import__(module)
annotator_webclient |   File "/workspace/webserver/__init__.py", line 5, in <module>
annotator_webclient |     import workers
annotator_webclient |   File "/workspace/workers/__init__.py", line 5, in <module>
annotator_webclient |     connect_mongo('Celery Worker')
annotator_webclient |   File "/workspace/database/__init__.py", line 20, in connect_mongo
annotator_webclient |     connect(name, host=host)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/mongoengine/connection.py", line 376, in connect
annotator_webclient |     register_connection(alias, db, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/mongoengine/connection.py", line 193, in register_connection
annotator_webclient |     **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/mongoengine/connection.py", line 86, in _get_connection_settings
annotator_webclient |     _check_db_name(conn_settings['name'])
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/mongoengine/connection.py", line 44, in _check_db_name
annotator_webclient |     _check_name(name)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 52, in _check_name
annotator_webclient |     "character %r" % invalid_char)
annotator_webclient | pymongo.errors.InvalidName: database names cannot contain the character ' '
```

**Comment by matt-deboer** [comment]
Note: This problem was encountered when I attempted to rebuild `backend/Dockerfile`; it probably won't be hit until that happens, since the python deps are cached from whenever that was last built.

I also hit problems with maskrcnn and dextr repos (due to the recent release of tensorflow 2.0), and had to fix those by modifying their respective `requirements.txt` files to pin tensorflow and keras to working versions (example):
```
RUN git clone --single-branch --depth 1 https://github.com/matterport/Mask_RCNN.git /tmp/maskrcnn && \
    cd /tmp/maskrcnn && \
    sed -i'' 's/tensorflow.*/tensorflow==1.12/; s/keras.*/keras==2.1.6/' ./requirements.txt && \
    pip install -r requirements.txt && \
    python3 setup.py install

# Install DEXTR
RUN git clone --single-branch --depth 1 https://github.com/jsbroks/dextr-keras.git /tmp/dextr  && \
    cd /tmp/dextr && \
    sed -i'' 's/tensorflow.*/tensorflow==1.12/; s/keras.*/keras==2.1.6/' ./requirements.txt && \
    pip install -r requirements.txt && \
    python setup.py install
```
