### ISSUE TITLE
Unable to download COCO dataset after export

### ISSUE THREAD

**Issue by GeorgeSeif** [jsbroks/coco-annotator#289]
Hello,

My team has deployed the coco annotator on an AWS server. As of late, we have been frequently getting a 500 status error (via google chrome inspect - Network tab) when trying to download the COCO annotations after exporting. We did some digging and also found this error log (some folder and dataset names changed for privacy):

```
[2019-11-11 14:59:12 +0000] [47] [ERROR] Exception on /api/image/2424 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 135, in get
    pil_image = image.thumbnail() if thumbnail else Image.open(image.path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/data_1/folder_1/data_1_folder_1_image (1).jpg'
[2019-11-11 14:59:12 +0000] [47] [DEBUG] GET /img/404-image.36797a63.png
[2019-11-11 14:59:12 +0000] [47] [ERROR] Exception on /api/image/12321 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFile.py", line 224, in load
    s = read(self.decodermaxblock)
  File "/usr/local/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 652, in load_read
    cid, pos, length = self.png.read()
  File "/usr/local/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 122, in read
    length = i32(s)
  File "/usr/local/lib/python3.6/site-packages/PIL/_binary.py", line 77, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/images.py", line 138, in get
    pil_image.thumbnail((width, height), Image.ANTIALIAS)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2143, in thumbnail
    im = self.resize(size, resample)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 1817, in resize
    self.load()
  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFile.py", line 230, in load
    raise IOError("image file is truncated")
OSError: image file is truncated
[2019-11-11 14:59:22 +0000] [47] [DEBUG] GET /
[2019-11-11 14:59:22 +0000] [47] [DEBUG] Closing connection.
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/dataset/96/data
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26041
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26056
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26051
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26055
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26050
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26058
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26060
[2019-11-11 14:59:24 +0000] [47] [DEBUG] GET /api/image/26047
[2019-11-11 14:59:30 +0000] [47] [DEBUG] GET /api/dataset/96/exports
[2019-11-11 14:59:32 +0000] [47] [DEBUG] GET /api/export/46/download
[2019-11-11 14:59:32 +0000] [47] [ERROR] Exception on /api/export/46/download [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/workspace/webserver/api/exports.py", line 70, in get
    return send_file(export.path, attachment_filename=f"{dataset.name}-{'-'.join(export.tags)}.json", as_attachment=True)
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/data_2/folder_2/.exports/coco-1573240423.4874449.json'
```

It seems to happen unpredictably, as sometimes we can download and other times we cannot. 

Any ideas as to how we can fix that?

Thanks you!

**Comment by EtienneDavid** [comment]
Maybe it's linked with how the data is sync between the file system and the docker image ?
