### ISSUE TITLE
Exporte half-way work

### ISSUE THREAD

**Issue by dawei22** [jsbroks/coco-annotator#385]
Hi!

When i want to export (Export COCO button or Download COCO) labels but i haven't finished labelling all images, an error raise and task get stucked :

```sh
annotator_workers | [2020-06-10 02:03:41,981: ERROR/ForkPoolWorker-8] Task workers.tasks.data.export_annotations[44aa693a-21a2-4b5a-8bfc-df1b89126d3d] raised unexpected: TypeError("'>' not supported between instances of 'numpy.ndarray' and 'int'",)
annotator_workers | Traceback (most recent call last):
annotator_workers |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
annotator_workers |     R = retval = fun(*args, **kwargs)
annotator_workers |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
annotator_workers |     return self.run(*args, **kwargs)
annotator_workers |   File "/workspace/workers/tasks/data.py", line 102, in export_annotations
annotator_workers |     annotation['num_keypoints'] = len(arr[arr > 0])
annotator_workers | TypeError: '>' not supported between instances of 'numpy.ndarray' and 'int'
```

![image](https://user-images.githubusercontent.com/14628860/84221035-4bb81300-aaa2-11ea-8caf-574217e786df.png)

If i download one per one it's okay. 

Is not possible download labels until i finished everything?

**Comment by jsbroks** [comment]
Seems to be an error in the export process

**Comment by kesaroid** [comment]
Hello, I am still facing the same issue, export stops midway due to the same error and starts missing heartbeats when trying to annotate keypoints.
