### ISSUE TITLE
docker version gives error : no address found

### ISSUE THREAD

**Issue by smoothumut** [jsbroks/coco-annotator#440]
Hi, When I try to install the docker image  on docker, it gives error, the log says: 

[2020-12-15 06:35:06 +0000] [7] [INFO] Starting gunicorn 19.9.0
[2020-12-15 06:35:06 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2020-12-15 06:35:06 +0000] [7] [INFO] Using worker: eventlet
[2020-12-15 06:35:06 +0000] [10] [INFO] Booting worker with pid: 10
[2020-12-15 06:35:07 +0000] [10] [WARNING] MaskRCNN model is disabled.
[2020-12-15 06:35:07 +0000] [10] [WARNING] DEXTR model is disabled.
[2020-12-15 06:35:37 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
super(EventletWorker, self).init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
__import__(module)
File "/workspace/app/__init__.py", line 50, in <module>
app = create_app()
File "/workspace/app/__init__.py", line 45, in create_app
ImageModel.objects.update(annotating=[])
File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
queryset = queryset_class(owner, owner._get_collection())
File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 208, in _get_collection
db.client.is_primary:
File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 857, in is_primary
return self._server_property('is_writable')
File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 689, in _server_property
writable_server_selector)
File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 224, in select_server
address))
File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 183, in select_servers
selector, server_timeout, address)
File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: database:27017: [Errno -2] No address found

After getting this error, I have installed MongoDB but still no luck : (

**Comment by viotemp1** [comment]
I gave the same error. Any hint please?

**Comment by aaronpp65** [comment]
stop and then restart mongodb
