### ISSUE TITLE
INITIALIZE_FROM_FILE requires a 'current_user'

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#67]
Related to #50, it looks like this feature may have been broken in recent user-based changes.

Specifically:
```
[ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/workspace/app/__init__.py", line 61, in <module>
    create_from_json(Config.INITIALIZE_FROM_FILE)
  File "/workspace/app/models.py", line 374, in create_from_json
    upsert(DatasetModel, query={ "name": name}, update=dataset_json)
  File "/workspace/app/models.py", line 347, in upsert
    new_model.save()
  File "/workspace/app/models.py", line 45, in save
    self.owner = current_user.username
  File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'NoneType' object has no attribute 'username'
```

It looks like in `models.py:45`, 
```
self.owner = current_user.username
```
there will not be any `current_user` available when the app is initializing; maybe there should be a special 'system' owner? Or perhaps the `initializer.json` file could contain a user section which would associate the datasets/categories created with a particular user...

Or maybe this feature should just be replaced with an API call so it will always have an associated user?
Then again, that would create a need to manually create users before being able to use the API...probably at least need a builtin `admin` account for such bootstrap concerns...

**Comment by matt-deboer** [comment]
@jsbroks I'm thinking the best approach is to add a built-in `admin` user with a password configured via environment variables--then, use this account for bootstrapping concerns via API calls.

So, if the env `ADMIN_PASSWORD` is specified, then an admin user is created on startup with that password, defaulting to username `admin` (overridden via env `ADMIN_USERNAME`).
Then, the effects of INITIALIZE_FROM_FILE can be accomplished with normal api calls.

What do you think?

**Comment by jsbroks** [comment]
I'm not quite for the idea of adding users using environment variables as it starts to complicate the experience.

Even adding a simple line such as:

```python
username = current.username
... = username if username else "system"
```

would be a simple fix.

**Comment by matt-deboer** [comment]
ok, sounds good. PR coming shortly.
